kind: ConfigMap
apiVersion: v1
metadata:
  name: test-config-map-file
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <title>test</title>
    </head>
    <body>
      <h1>It actually works!</h1>
    </body>
    </html>
