apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
spec:
  containers:
    - name: mysqlcontainer
      image: mysql:8
      env:
        # dit is eigenlijk bad practice
        # een Secret is geschikter
        # maar MySQL containers vereisen deze variabele
        # en Secrets bekijken we later
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: envvarexamplemap
              key: mysqlrootpassword
