apiVersion: v1
kind: Pod
metadata:
  name: secrets-test-pod
  labels:
    app: secrets-test
spec:
  volumes:
    - name: volumeforsecrets
      secret:
        secretName: mycredentials
  containers:
    - name: idler
      image: busybox
      volumeMounts:
        - name: volumeforsecrets
          mountPath: "/etc/credentials"
      command: ["sleep", "infinity"]
