apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-nginx
  template:
    metadata:
      labels:
        app: manual-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: volume-from-configmap
            mountPath: /etc/nginx
      volumes:
        - name: volume-from-configmap
          configMap:
            name: manual-nginx-conf-configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: manual-nginx-conf-configmap
data:
  nginx.conf: |
    events {}
    
    http {
        upstream app1-service {
            server app1-service:80;
        }
    
        upstream app2-service {
            server app2-service:80;
        }
    
        server {
            listen 80;
            server_name app1.demowebsite.com;
    
            location / {
                proxy_pass http://app1-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    
        server {
            listen 80;
            server_name app2.demowebsite.com;
    
            location / {
                proxy_pass http://app2-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
spec:
  type: NodePort
  selector:
    app: manual-nginx
  ports:
  - port: 80 # poort van de service voor intern in de cluster, dus niet zo belangrijk
    targetPort: 80 # poort waarop een NGINX container luistert
    nodePort: 30001 # waar we naartoe moeten surfen
---
apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
  labels:
    app: app1
spec:
  volumes:
    - name: app1-volume
      configMap:
        name: app1-config
  containers:
  - name: app1-container
    image: httpd:2.4
    ports:
      - containerPort: 80
    volumeMounts:
      - name: app1-volume
        mountPath: /usr/local/apache2/htdocs
---
apiVersion: v1
kind: Pod
metadata:
  name: app2-pod
  labels:
    app: app2
spec:
  volumes:
    - name: app2-volume
      configMap:
        name: app2-config
  containers:
  - name: app2-container
    image: httpd:2.4
    ports:
      - containerPort: 80
    volumeMounts:
      - name: app2-volume
        mountPath: /usr/local/apache2/htdocs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <title>app1</title>
    </head>
    <body>
      <h1>App1 works!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <title>app2</title>
    </head>
    <body>
      <h2>App2 works!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 80
